# Generated by Django 3.2.16 on 2023-02-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_ingredient_instructions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instructions',
            new_name='Instruction',
        ),
    ]
