# Generated by Django 3.2.16 on 2023-02-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_instructions_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
