# Generated by Django 3.2.16 on 2023-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingredient_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='dish',
            field=models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Snack'), (3, 'Dinner'), (4, 'Dessert')], default=3),
        ),
        migrations.AddField(
            model_name='post',
            name='prep',
            field=models.IntegerField(default=0),
        ),
    ]
