# Generated by Django 3.2.16 on 2023-02-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_alter_instruction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='detail',
            field=models.CharField(max_length=800),
        ),
    ]
