# Generated by Django 3.2.16 on 2023-02-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_instruction_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='detail',
            field=models.TextField(),
        ),
    ]
